Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\courses\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\courses\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\fahima\Desktop\final\final_project\users\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 183377
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 183377
Watching for file changes with StatReloader
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 183377
Internal Server Error: /v1/student_requests/assistant/5/studying-evidence/2/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py", line 873, in get_object
    request = get_object_or_404(MilitaryServiceRequest, student_id=student_id)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 500 181698
"POST /v1/users/login/ HTTP/1.1" 200 69
Method Not Allowed: /v1/student_requests/assistant/5/studying-evidence/2/
"PATCH /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 405 42
Watching for file changes with StatReloader
"GET /my-admin HTTP/1.1" 301 0
"GET /my-admin/ HTTP/1.1" 200 18291
"GET /my-admin/ HTTP/1.1" 200 18291
Not Found: /en/my-admin/
"GET /en/my-admin/ HTTP/1.1" 404 3441
"GET /my-admin/ HTTP/1.1" 200 18291
Not Found: /admin/
"GET /admin/ HTTP/1.1" 404 5828
Not Found: /admin/
"GET /admin/ HTTP/1.1" 404 5828
Method Not Allowed: /v1/student_requests/assistant/5/studying-evidence/2/
"PATCH /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 405 42
Watching for file changes with StatReloader
Method Not Allowed: /v1/student_requests/assistant/5/studying-evidence/2/
"PATCH /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 405 42
Internal Server Error: /v1/student_requests/assistant/5/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/assistant/5/studying-evidence/ HTTP/1.1" 500 180516
C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /v1/student_requests/assistant/5/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/assistant/5/studying-evidence/ HTTP/1.1" 500 180516
Internal Server Error: /v1/student_requests/assistant/5/studying-evidence/2/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py", line 873, in get_object
    request = get_object_or_404(MilitaryServiceRequest, student_id=student_id)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: student_requests_militaryservicerequest.deputy_educational_id
"GET /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 500 181698
"POST /v1/users/login/ HTTP/1.1" 200 69
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py", line 573, in perform_create
    serializer.save(student=student_instance)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\serializers.py", line 201, in create
    military_service_request = MilitaryServiceRequest.objects.create(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id
"POST /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 209069
Watching for file changes with StatReloader
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py", line 573, in perform_create
    serializer.save(student=student_instance)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\serializers.py", line 201, in create
    military_service_request = MilitaryServiceRequest.objects.create(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id
"POST /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 209069
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /my-admin/ HTTP/1.1" 200 18291
"GET /my-admin/authtoken/tokenproxy/ HTTP/1.1" 200 15703
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /my-admin/ HTTP/1.1" 200 18291
Bad Request: /v1/users/register/
"POST /v1/users/register/ HTTP/1.1" 400 58
Internal Server Error: /v1/student_requests/student/2/studying-evidence/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py", line 573, in perform_create
    serializer.save(student=student_instance)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\serializers.py", line 201, in create
    military_service_request = MilitaryServiceRequest.objects.create(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table student_requests_militaryservicerequest has no column named deputy_educational_id
"POST /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 500 209069
C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\models.py changed, reloading.
Watching for file changes with StatReloader
"POST /v1/student_requests/student/2/studying-evidence/ HTTP/1.1" 201 142
C:\Users\ASUS\Desktop\quera\Django Bootcamp\final_project\student_requests\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /v1/student_requests/assistant/5/studying-evidence/2/
"PATCH /v1/student_requests/assistant/5/studying-evidence/2/ HTTP/1.1" 405 42
